pipeline:
  eslint:
    image: nextcloudci/eslint:eslint-1
    commands:
      - ./run-eslint.sh
    when:
      matrix:
        TESTS: eslint
  stylelint:
    image: nextcloudci/stylelint:stylelint-1
    commands:
      - ./run-stylelint.sh
    when:
      matrix:
        TESTS: stylelint
  check-app-compatbility:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=spreed
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server

      # Code checker
      - ./occ app:check-code $APP_NAME
      - cd apps/$APP_NAME/
    when:
      matrix:
        TESTS: check-app-compatbility
  syntax-php7.0:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=spreed
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - composer install
      - ./lib/composer/bin/parallel-lint apps/$APP_NAME/
    when:
      matrix:
        TESTS: syntax-php7.0
  signed-off-check:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=spreed
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php ./build/signed-off-checker.php
    when:
      matrix:
        TESTS: signed-off-check
  php7.0:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=spreed
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/php/
      - phpunit --configuration phpunit.xml
    when:
      matrix:
        TESTS: php7.0
  php7.1:
    image: nextcloudci/php7.1:php7.1-15
    environment:
      - APP_NAME=spreed
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/php/
      - phpunit --configuration phpunit.xml
    when:
      matrix:
        TESTS: php7.1
  php7.2:
    image: nextcloudci/php7.2:php7.2-9
    environment:
      - APP_NAME=spreed
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/php/
      - phpunit --configuration phpunit.xml
    when:
      matrix:
        TESTS: php7.2
  php7.1-integration:
    image: nextcloudci/php7.1:php7.1-15
    environment:
      - APP_NAME=spreed
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run integration tests
      - cd tests/integration/
      - bash run.sh
    when:
      matrix:
        TESTS: php7.1-integration
  jsunit:
    image: nextcloudci/jsunit:jsunit-5
    commands:
      - unset PHANTOMJS_BIN
      - npm install
      - node_modules/karma/bin/karma start --single-run
    when:
      matrix:
        TESTS: jsunit

matrix:
  include:
    - TESTS: eslint
    - TESTS: stylelint
    - TESTS: check-app-compatbility
    - TESTS: syntax-php7.0
    - TESTS: signed-off-check
    - TESTS: php7.0
    - TESTS: php7.1
    - TESTS: php7.2
    - TESTS: php7.1-integration
    - TESTS: jsunit
